### ISSUE TITLE
Apache Drill Query Execution PLAN Doesn't use mongo db index

### ISSUE THREAD

**Issue by dwevedivaibhav** [apache/drill#2826] opened 2023-08-25 08:35 UTC
Hi Team,

I am trying to execute the millions of record query from mongo db storage with timestamp filter, it getting slow even though i created the index of timestamp in mongo collection, but its taking so long time to execute and some time time its failing also due to huge record. 

Please find the sample query which i am executing from apache drill

select  * FROM `mongo`.`sampletable`
WHERE `SentTime` >= TO_TIMESTAMP('2023-08-10 00:00:00', 'yyyy-MM-dd HH:mm:ss')
  AND `SentTime` < TO_TIMESTAMP('2023-08-17 00:00:00', 'yyyy-MM-dd HH:mm:ss')
LIMIT 10

**Comment by jnturton** [comment] 2023-08-25 08:42
I wonder if your constant timestamp expressions are being folded by the planner. Do you get the same performance from the next query?

```sql
SELECT * FROM mongo.sampletable
WHERE SentTime >= TIMESTAMP '2023-08-10 00:00:00'
AND SentTime < TIMESTAMP '2023-08-17 00:00:00'
LIMIT 10
```

**Comment by dwevedivaibhav** [comment] 2024-04-24 09:09
Yes Same problem @jnturton

**Comment by jnturton** [comment] 2024-04-25 06:12
Duplicate of #2906.

**Closed** 2024-04-25 06:11 UTC
Labels: bug
